seed: 42
epochs: 20
image_size: 224
batch_size: 76
label_smooth:

loss:
  type: focal

  focal:
    gamma: 2.0

model:
  type: seresnext50
  predict_thresh: False
  dropout: 0.2

aug:
  type: rpad
  scale: True
  color:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.3
    hue: 0.
  crop_scale: 0.875 # 224 / 256

opt:
  type: adam
  lr: 5e-4
  beta: 0.9
  weight_decay: 1e-4

sched:
  type: onecycle

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]

