seed: 42
epochs: 10
image_size: 224
batch_size: 76
label_smooth:

loss:
  type: focal

  focal:
    gamma: 2.0

model:
  type: seresnext50
  predict_thresh: False
  dropout:

aug:
  type: rpad
  scale: True
  color: 0.3
  crop_scale: 0.875 # 224 / 256

opt:
  type: adam
  lr: 1e-3
  beta: 0.9
  weight_decay: 1e-4

sched:
  type: onecycle

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]

