seed: 42
epochs: 10
image_size: 224
batch_size: 4 # FIXME:
focal_gamma: 2.0
label_smooth:

model:
  type: seresnext50
  predict_thresh: False

aug:
  type: pad
  aspect: false
  crop_scale: 0.875 # 224 / 256

opt:
  type: adam
  lr:
  beta: 0.9
  weight_decay: 1e-4

sched:
  type: onecycle

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]
