seed: 42
epochs: 10
image_size: 224
batch_size: 4
label_smooth:
mixup:

loss:
  type: lsep

  focal:
    gamma: 2.0

model:
  type: seresnext50
  predict_thresh: True
  dropout: 0.2

aug:
  type: rpad
  crop_scale: 0.875 # 224 / 256
  scale: True
  color:
    brightness: 0.3
    contrast: 0.3
    saturation: 0.3
    hue: 0.
  cutout:
    n_holes: 1
    length: 0.5

opt:
  type: adam
  lr:
  beta: 0.9
  weight_decay: 1e-4

sched:
  type: onecycle

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]


