seed: 42
epochs: 1000
batch_size: 300
resize_size: 256
image_size: 224

model:

opt:
  type: sgd
  lr: 0.1
  weight_decay: 1e-5

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: cyclic

  step:
    decay: 0.99
    step_size: 100

  plateau:
    decay: 0.1
    patience: 2

  cyclic:
    step_size_up: 2
    step_size_down: 2
    decay: 0.75

