seed: 42
epochs: 50
batch_size: 16
resize_size: 512
crop_size: 512
normalize: experiment
progressive_resize: True

model:
  type: efficientnet-b0

aug:
  channel_weight: 0.5

opt:
  type: radam
  lr: 0.001
  weight_decay: 1e-4
  acc_steps: 4

  lookahead:

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: step

  step:
    decay: 0.1
    step_size: 15

  plateau:
    decay: 0.5
    patience: 5

  cyclic:
    step_size_up: 2
    step_size_down: 2
    decay: 0.75

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]
    peak_pos: 0.45
    end_pos: 0.9
