seed: 42
epochs: 50
batch_size: 56
resize_size: 274
image_size: 240

model:
  type: b1

aug:
  channel_weight: 0.5

opt:
  type: sgd
  lr: 0.6
  weight_decay: 1e-4

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: onecycle

  step:
    decay: 0.99
    step_size: 100

  plateau:
    decay: 0.5
    patience: 5

  cyclic:
    step_size_up: 2
    step_size_down: 2
    decay: 0.75

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]
    peak_pos: 0.4
    end_pos: 0.8
