seed: 42
epochs: 50
batch_size: 16
resize_size: 512
crop_size:
  min: 512
  max: 512
normalize: experiment
progressive_resize: True

model:
  type: efficientnet-b5

aug:
  channel_reweight: 0.3

opt:
  type: radam
  lr: 0.000075
  weight_decay: 1e-4
  acc_steps: 4

  lookahead:
    lr: 0.5
    steps: 5

  ewa:
    momentum: 0.9
    steps: 5

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: plateau

  step:
    decay: 0.5
    step_size: 5

  plateau:
    decay: 0.5
    patience: 3

  cyclic:
    step_size_up: 2
    step_size_down: 2
    decay: 0.75

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]
    peak_pos: 0.45
    end_pos: 0.9
