seed: 42
epochs: 70
batch_size: 200
resize_size: 256
image_size: 224

model:
  dropout: 0.2

aug:
  channel_weight: 0.5

opt:
  type: sgd
  lr: 0.14
  weight_decay: 1e-4

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: onecycle

  step:
    decay: 0.99
    step_size: 100

  plateau:
    decay: 0.1
    patience: 2

  cyclic:
    step_size_up: 2
    step_size_down: 2
    decay: 0.75

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]
