seed: 42
epochs: 1000
batch_size: 2
# dropout: 0.8

opt:
  type: sgd
  lr: 0.1
  weight_decay: 1e-5

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: cawr

  step:
    decay: 0.99
    step_size: 3

