seed: 42
epochs: 1000
batch_size: 170

opt:
  type: rmsprop
  lr: 0.0002
  weight_decay: 1e-5

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: plateau

  step:
    decay: 0.99
    step_size: 100

  plateau:
    decay: 0.1
    patience: 2

