seed: 42
epochs: 100
batch_size: 8
image_size: 512
train_size: 10000

opt:
  type: sgd
  lr: 0.01
  weight_decay: 1e-4
  acc_steps: 2

  sgd:
    momentum: 0.9

sched:
  type: multistep

  multistep:
    steps: [100]
