seed: 42
epochs: 50
batch_size: 8
image_size: 512
train_size: 1000

anchors:
  min_iou: 0.4
  max_iou: 0.5
  sizes:
    -
    -
    -
    - 32
    - 64
    - 128
    - 256
    - 512
  ratios:
    - 0.5
    - 1
    - 2
  scales:
    - 1
    - 1.26
    - 1.587

opt:
  type: sgd
  lr: 0.01
  weight_decay: 1e-4
  acc_steps: 2

  sgd:
    momentum: 0.9

sched:
  type: cosine

  multistep:
    steps: [30]

