seed: 42
epochs: 100
batch_size: 8
image_size: 600
train_size: 8000

opt:
  type: sgd
  lr: 0.02
  weight_decay: 1e-4
  acc_steps: 4

    lookahead:
      lr: 0.5
      steps: 5

  sgd:
    momentum: 0.9

sched:
  type: multistep

  multistep:
    steps: [100]
