seed: 42
epochs: 32
batch_size: 100
image_size: 1024
mixup:

model:
  type: max
  dropout: 0.2

aug:
  type: crop

opt:
  type: momentum
  lr: 32e-4
  beta: 0.9
  weight_decay: 1e-4

sched:
  type: cyclic

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]

  cyclic:
    beta: [0.9, 0.8]


