seed: 42
epochs: 30
finetune_epoch: 25
batch_size: 24
mixup:

model:
  type: resnet18-maxpool-1d
  dropout: 0.2
  sample_rate: 44100

aug:
  type: crop

  crop:
    size: 15

  split_concat:
    min_size: 1

  cutout:
    fraction: 0.1

  effects: False
  spec_aug: False

opt:
  type: adam
  lr: 8e-4
  beta: 0.9
  weight_decay: 1e-4

sched:
  type: onecycle

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]

  cyclic:
    beta: [0.9, 0.8]

