seed: 42
epochs: 1000
batch_size: 16
image_size: 320

model:

opt:
  type: sgd
  lr: 0.2
  weight_decay: 1e-4
  acc_steps: 4

  lookahead:

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: plateau

  step:
    decay: 0.99
    step_size: 100

  plateau:
    decay: 0.1
    patience: 10

