seed: 42
epochs: 100
batch_size: 24

model:

opt:
  type: adam
  lr: 1e-4
  weight_decay: 1e-4
  acc_steps: 4

  lookahead:
    lr: 0.5
    steps: 5

  sgd:
    momentum: 0.9

  rmsprop:
    momentum: 0.9

sched:
  type: plateau

  step:
    decay: 0.99
    step_size: 100

  plateau:
    decay: 0.5
    patience: 5

  cyclic:
    step_size_up: 2
    step_size_down: 2
    decay: 0.75

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]
    peak_pos: 0.45
    end_pos: 0.9

