seed: 42
epochs: 50
batch_size: 256

model:
  size: 256

opt:
  type: adam
  lr: 1e-2
  beta: 0.9
  weight_decay: 1e-7

sched:
  type: plateau

  onecycle:
    anneal: linear
    beta: [0.95, 0.85]



